language: generic
os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - lib32stdc++6

before_script:
  - ./.travis/before_script.sh

script:
  - ./.travis/script.sh

cache:
  directories:
    - $HOME/flutter
    - $HOME/.pub-cache
