name: fancy_button
description: A spiffy little button widget
version: 0.1.0
author: Tyler Filla
homepage: https://github.com/tylerfilla/fancy_button

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
